### ISSUE TITLE
Error at start up in django container

### ISSUE THREAD

**Issue by Aledan862** [olimpo88/PyDDNS#12]
Log tails

postgres_1  | CREATE DATABASE
postgres_1  |
postgres_1  |
postgres_1  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgres_1  |
postgres_1  | waiting for server to shut down....LOG:  received fast shutdown request
postgres_1  | LOG:  aborting any active transactions
postgres_1  | LOG:  autovacuum launcher shutting down
postgres_1  | LOG:  shutting down
postgres_1  | LOG:  database system is shut down
postgres_1  |  done
postgres_1  | server stopped
postgres_1  |
postgres_1  | PostgreSQL init process complete; ready for start up.
postgres_1  |
postgres_1  | LOG:  database system was shut down at 2020-08-08 23:31:17 UTC
postgres_1  | LOG:  MultiXact member wraparound protections are now enabled
postgres_1  | LOG:  database system is ready to accept connections
postgres_1  | LOG:  autovacuum launcher started
postgres_1  | LOG:  incomplete startup packet
python_1    | wait-for-it.sh: postgres:5432 is available after 8 seconds
python_1    | Traceback (most recent call last):
python_1    |   File "manage.py", line 10, in <module>
python_1    |     execute_from_command_line(sys.argv)
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
python_1    |     utility.execute()
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
python_1    |     self.fetch_command(subcommand).run_from_argv(self.argv)
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 330, in run_from_argv
python_1    |     self.execute(*args, **cmd_options)
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 368, in execute
python_1    |     self.check()
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 396, in check
python_1    |     databases=databases,
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/checks/registry.py", line 70, in run_checks
python_1    |     new_errors = check(app_configs=app_configs, databases=databases)
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/checks/urls.py", line 13, in check_url_config
python_1    |     return check_resolver(resolver)
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/checks/urls.py", line 23, in check_resolver
python_1    |     return check_method()
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/urls/resolvers.py", line 408, in check
python_1    |     for pattern in self.url_patterns:
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
python_1    |     res = instance.__dict__[self.name] = self.func(instance)
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/urls/resolvers.py", line 589, in url_patterns
python_1    |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
python_1    |     res = instance.__dict__[self.name] = self.func(instance)
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
python_1    |     return import_module(self.urlconf_name)
python_1    |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
python_1    |     return _bootstrap._gcd_import(name[level:], package, level)
python_1    |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
python_1    |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
python_1    |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
python_1    |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
python_1    |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
python_1    |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
python_1    |   File "/usr/src/app/pyddns/urls.py", line 19, in <module>
python_1    |     from common.views import *
python_1    |   File "/usr/src/app/common/views.py", line 12, in <module>
python_1    |     from common.utils import getForwardedFor
python_1    |   File "/usr/src/app/common/utils.py", line 5, in <module>
python_1    |     from django.forms.forms import BoundField
python_1    | ImportError: cannot import name 'BoundField' from 'django.forms.forms' (/usr/local/lib/python3.7/site-packages/django/forms/forms.py)
python_1    | Traceback (most recent call last):
python_1    |   File "manage.py", line 10, in <module>
python_1    |     execute_from_command_line(sys.argv)
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
python_1    |     utility.execute()
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
python_1    |     self.fetch_command(subcommand).run_from_argv(self.argv)
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 330, in run_from_argv
python_1    |     self.execute(*args, **cmd_options)
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 371, in execute
python_1    |     output = self.handle(*args, **options)
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 85, in wrapped
python_1    |     res = handle_func(*args, **kwargs)
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 75, in handle
python_1    |     self.check(databases=[database])
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 396, in check
python_1    |     databases=databases,
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/checks/registry.py", line 70, in run_checks
python_1    |     new_errors = check(app_configs=app_configs, databases=databases)
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/checks/urls.py", line 13, in check_url_config
python_1    |     return check_resolver(resolver)
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/checks/urls.py", line 23, in check_resolver
python_1    |     return check_method()
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/urls/resolvers.py", line 408, in check
python_1    |     for pattern in self.url_patterns:
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
python_1    |     res = instance.__dict__[self.name] = self.func(instance)
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/urls/resolvers.py", line 589, in url_patterns
python_1    |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
python_1    |     res = instance.__dict__[self.name] = self.func(instance)
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
python_1    |     return import_module(self.urlconf_name)
python_1    |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
python_1    |     return _bootstrap._gcd_import(name[level:], package, level)
python_1    |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
python_1    |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
python_1    |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
python_1    |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
python_1    |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
python_1    |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
python_1    |   File "/usr/src/app/pyddns/urls.py", line 19, in <module>
python_1    |     from common.views import *
python_1    |   File "/usr/src/app/common/views.py", line 12, in <module>
python_1    |     from common.utils import getForwardedFor
python_1    |   File "/usr/src/app/common/utils.py", line 5, in <module>
python_1    |     from django.forms.forms import BoundField
python_1    | ImportError: cannot import name 'BoundField' from 'django.forms.forms' (/usr/local/lib/python3.7/site-packages/django/forms/forms.py)
postgres_1  | ERROR:  relation "auth_user" does not exist at character 24
postgres_1  | STATEMENT:  SELECT (1) AS "a" FROM "auth_user" WHERE "auth_user"."username" = 'admin' LIMIT 1
python_1    | Traceback (most recent call last):
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
python_1    |     return self.cursor.execute(sql, params)
python_1    | psycopg2.errors.UndefinedTable: relation "auth_user" does not exist
python_1    | LINE 1: SELECT (1) AS "a" FROM "auth_user" WHERE "auth_user"."userna...
python_1    |                                ^
python_1    |
python_1    |
python_1    | The above exception was the direct cause of the following exception:
python_1    |
python_1    | Traceback (most recent call last):
python_1    |   File "manage.py", line 10, in <module>
python_1    |     execute_from_command_line(sys.argv)
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
python_1    |     utility.execute()
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
python_1    |     self.fetch_command(subcommand).run_from_argv(self.argv)
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 330, in run_from_argv
python_1    |     self.execute(*args, **cmd_options)
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 371, in execute
python_1    |     output = self.handle(*args, **options)
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/shell.py", line 92, in handle
python_1    |     exec(sys.stdin.read())
python_1    |   File "<string>", line 1, in <module>
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 809, in exists
python_1    |     return self.query.has_results(using=self.db)
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/query.py", line 535, in has_results
python_1    |     return compiler.has_results()
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1124, in has_results
python_1    |     return bool(self.execute_sql(SINGLE))
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1154, in execute_sql
python_1    |     cursor.execute(sql, params)
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 98, in execute
python_1    |     return super().execute(sql, params)
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 66, in execute
python_1    |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
python_1    |     return executor(sql, params, many, context)
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
python_1    |     return self.cursor.execute(sql, params)
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
python_1    |     raise dj_exc_value.with_traceback(traceback) from exc_value
python_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
python_1    |     return self.cursor.execute(sql, params)
python_1    | django.db.utils.ProgrammingError: relation "auth_user" does not exist
python_1    | LINE 1: SELECT (1) AS "a" FROM "auth_user" WHERE "auth_user"."userna...
python_1    |                                ^
python_1    |
python_1    | Watching for file changes with StatReloader

**Comment by olimpo88** [comment]
that is not normal, apparently there is an error when creating the database, it is an automatic process
please try the following:

`docker-compose down`
`docker-compose up`


If this does not solve your error, try deleting the database to recreate it.

`docker-compose down`
`sudo rm data/ -R`
`docker-compose up`

**Comment by Aledan862** [comment]
I've tried your suggestion but still get the same error.
So
I resolve this ImportError: cannot import name 'BoundField' from 'django.forms.forms' (/usr/local/lib/python3.7/site-packages/django/forms/forms.py

Change 5 line in file /common/utils.py
`from django.forms.forms import BoundField` 
to
`from django.forms.boundfield import BoundField`

And after that, all migrations made successfully.

**Comment by olimpo88** [comment]
Thank you @Aledan862 . I can't replicate your error, can you tell me the version of python and django your server is running?


`docker-compose exec python bash`
`python --version`
`python -m django --version`

**Comment by Aledan862** [comment]
Python 3.7.8
Django 3.1

**Comment by yomono** [comment]
Im having the exact same error! 
Unfortunaly im not smart enough to find the /common/utild.py file and edit it :(

**Comment by olimpo88** [comment]
Perfect, thanks @Aledan862 
The problem was generated for django > 3.1
Apparently pip began these days to automatically install that version

I already made the change and force that is the minimum version for everyone.

**Comment by olimpo88** [comment]
> Im having the exact same error!
> Unfortunaly im not smart enough to find the /common/utild.py file and edit it :(

@yomono  if you never used PyDNS delete the project folder, re-clone it start again, it will take much less time than the first time.

**Comment by yomono** [comment]
Amazing! Actually i was just using a VPS just for this, so i just reinstalled. I can now access to the web admin. However, im having another error when tying to update a subdomain address. Should i open a new issue for this?

**Comment by olimpo88** [comment]
Yes, please, if this is resolved, I will leave the topic closed.
