### ISSUE TITLE
Self service sign up for users?

### ISSUE THREAD

**Issue by DSorlov** [olimpo88/PyDDNS#14]
I dont know what the plans are moving forward but to be able to easily create new users via self-service would be a terrific next step. Could for instance create accounts that are limited to a specific number of subdomains or something like that. Depending on your plans I would absolutely be interested in contributing this.

**Comment by olimpo88** [comment]
Currently the project is used by organizations, where the administrators
create the users, I understand that there are other needs, if you want to
contribute with a registration section, it would be ideal if it could be
activated with an environment variable.

Thank you very much for your contribution with the ssl :)

**Comment by DSorlov** [comment]
I could absolutely go for a stab into making that! I will be back as they say. =)

**Comment by DSorlov** [comment]
I have not had the time to come back to this yet. I have instead gone down another route with a NodeJS based server. Thanks for fantastic work however and good luck going forward!
