### ISSUE TITLE
cannot reload nginx while trying to execute the command sudo docker-compose up

### ISSUE THREAD

**Issue by sreenidhick** [olimpo88/PyDDNS#16]
When I am trying to execute the command sudo docker-compose up i am getting the error as cannot reload nginx. I am trying to implement this application on ubuntu 20.04. Error starting use
![Capture1231](https://user-images.githubusercontent.com/30571375/97374738-c2946200-1904-11eb-8dfc-231c5287216b.PNG)
rland proxy: listen tcp 0.0.0.0:80 bind: address already in use. Your feedback is much appreciated..

**Comment by olimpo88** [comment]
You probably have port 80 busy, check which service is on port 80:

netstat -tip | grep: 80

You can use another port for PYDDNS, you can set it in the .env file

**Comment by sreenidhick** [comment]
When I checked the status of the port 80 only the web server nginx is using that port number
![Capture23e2e2](https://user-images.githubusercontent.com/30571375/97377073-d5119a00-190a-11eb-8957-82fe15dc2ee6.PNG)

**Comment by sreenidhick** [comment]
If we are using any other port number say 3200 for PYDDNS, then we need to assign the same port number in /etc/nginx/sites-enabled. Can you please have a look and let me know whether I have configured it correctly as this would be more helpful for me..
![Captureqwewqewq](https://user-images.githubusercontent.com/30571375/97378677-a1d10a00-190e-11eb-8a42-747111b1573b.PNG)
![Captureqwewqewq33333](https://user-images.githubusercontent.com/30571375/97378686-a85f8180-190e-11eb-8db2-6e706af75041.PNG)

**Comment by olimpo88** [comment]
The port that you have configured in the .env file is already mapped to the nginx port.
You should not change the nginx configuration.

**Comment by sreenidhick** [comment]
I have tried by changing the port number to 3201 both in .env file and sites-enabled files in nginx but still I am getting the same error as bind address already in use. Please find the screen shot for your reference. Is there any way to fix the issue..
![Capture90](https://user-images.githubusercontent.com/30571375/97379980-d1cddc80-1911-11eb-8159-e40ba7c1b921.PNG)
![Capture91](https://user-images.githubusercontent.com/30571375/97379994-d72b2700-1911-11eb-918f-e10e836e1516.PNG)
![Capture903](https://user-images.githubusercontent.com/30571375/97380010-dd210800-1911-11eb-8220-cdd30d5e843a.PNG)

Can you please help me to sort out the issue..

**Comment by olimpo88** [comment]
Check if you don't have another docker running
`docker ps`

if so you can stop it with
`docker-compose down`

**Comment by sreenidhick** [comment]
> The port that you have configured in the .env file is already mapped to the nginx port.
> You should not change the nginx configuration.

Okay. thank you

**Comment by olimpo88** [comment]
Is your problem solved?

**Comment by sreenidhick** [comment]
> Check if you don't have another docker running
> `docker ps`
> 
> if so you can stop it with
> `docker-compose down`
> 
> and try `docker-compose up` again
> 
> Check for any other errors when you start the service.

No, still I am getting the error.

I don't have any other docker running and I have only changed the HTTP port number to 3201 and TCP to 54 in .env file. And tried to stop it by using the command docker-compose down and then docker-compose up but getting the error with port 3201 has been already allocated.
Do we need to change anything in docker.compose.yml file. Please find the screenshot for your reference.. It would be more helpful if you could help me in resolving it
![Capture5465654](https://user-images.githubusercontent.com/30571375/97385354-435f5800-191d-11eb-8f89-92adc2e50c13.PNG)
![Captureqwewqewq](https://user-images.githubusercontent.com/30571375/97385376-4a866600-191d-11eb-93ba-2473716bd69f.PNG)
![565225](https://user-images.githubusercontent.com/30571375/97385576-ab15a300-191d-11eb-905b-d181a1411d40.PNG)

**Comment by sreenidhick** [comment]
![Uploading 101.PNG…]()

**Comment by sreenidhick** [comment]
![101](https://user-images.githubusercontent.com/30571375/97385687-f039d500-191d-11eb-98d9-934cb1364f1b.PNG)

**Comment by sreenidhick** [comment]
I tried by assigning different port number but still getting the same error as port has been already allocated..

**Comment by sreenidhick** [comment]
> Is your problem solved?

No, I am getting the error stating port has been already allocated. I tried to assign different port number but no luck.

**Comment by sreenidhick** [comment]
Can you please help me in solving the error?

**Comment by olimpo88** [comment]
This is not normal, please send me a message at peraltaleandro88@gmail.com

**Comment by olimpo88** [comment]
Probably so many changes and file manipulation are influencing.
Please delete your Pyddns folder and start again following the steps, it should not take more than 5 minutes.

**Comment by sreenidhick** [comment]
> Verify that your ports HTTPS_PORT and HTTP_PORT in the .env file are not the same.

I have changed the port numbers. Now its not showing port allocation error. However, when I run docker-compose up its getting stuck after running it and also when tried to access the 127.0.0.1:3200 its showing as unable to connect
![image](https://user-images.githubusercontent.com/30571375/97509184-43b72c00-19cd-11eb-91ba-e083ad290373.png)
![image](https://user-images.githubusercontent.com/30571375/97509268-8b3db800-19cd-11eb-8f10-854a9a8ce1a0.png)

**Comment by olimpo88** [comment]
The problem is solved.

@sreenidhick I would appreciate if it could take 5 minutes and validate my knowledge (aptitudes). ballot_box_with_check
https://www.linkedin.com/in/peraltaleandro/

**Comment by olimpo88** [comment]
The problem is solved.

@sreenidhick I would appreciate if it could take 5 minutes and validate my knowledge (aptitudes). ballot_box_with_check
https://www.linkedin.com/in/peraltaleandro/
