### ISSUE TITLE
Adding Forward Zone

### ISSUE THREAD

**Issue by simonso1224** [olimpo88/PyDDNS#18]
Thanks for making the PyDDNS server available.

Just wondering if there is any way that I can use this server to resolve domains other than the ones locally by the server? Is there any way that I can set up forward zones to forward queries to a public DNS server?

**Comment by olimpo88** [comment]
Hi, simonso1224 this project does not solve that, that you could solve it with some service for example bind9 or dnmasq on your server.

**Comment by simonso1224** [comment]
Thanks for the reply. Maybe I should be a little more specific in my description.

I do need the functionality of having my own private DNS server, which is perfect for my case. I am needing the functionality of this project to do that. I can successfully point resources to use PyDDNS server as the primary DNS server, and I can resolve private DNS requests. However, on the same VMs, they would also need to access to the public Internet, which needs domain name resolution to domains like www.google.com, which is currently not covered in scope by this project.

If you can be kind to point me to the right direction of how I can do both on the same server, that would be great.

**Comment by olimpo88** [comment]
PyDDNS is not a DNS server, so it cannot be used as the primary.

PyDDNS is a dynamic DNS server, you need to install bind9 on your server for example, so you can have your local domains, resolve external domains and one of your domains or subdomains that must be dynamic in that case in your DNS create an NS record pointing to PyDDNS

**Comment by simonso1224** [comment]
Thank you very much for your suggestion. Will definitely research in this direction.

**Comment by olimpo88** [comment]
> Thank you very much for your suggestion. Will definitely research in this direction.

Perfect!!! @simonso1224 

The project is OpenSource, I spend many hours maintaining and updating it, I would appreciate if you could take 5 minutes and validate my knowledge. (aptitudes). :ballot_box_with_check:
https://www.linkedin.com/in/peraltaleandro/
