### ISSUE TITLE
Error after run docker-compose up, "pyddns_nginx_1 exited with code 1"

### ISSUE THREAD

**Issue by anhvlhy** [olimpo88/PyDDNS#19]
Error in detail:
nginx_1     | 2020/12/03 04:50:50 [emerg] 1#1: cannot load certificate "/etc/nginx/certs/https.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/certs/https.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
I cant start web of PyDDNS, I dont know how to resolve it, could you support please

**Comment by olimpo88** [comment]
Hi @anhvlhy
Please validate that you created the certificate, see the instructions to find them. Verify that they are found in the data/certs folder

**Comment by olimpo88** [comment]
no answer, for a considerable time
If you need it please open another query
