### ISSUE TITLE
ddclient update problem 

### ISSUE THREAD

**Issue by cpedja** [olimpo88/PyDDNS#21]
Hi

on server i receive this message 

x.x.x.x - user [10/Mar/2021:11:32:40 +0000] "GET /nic/update?system=dyndns&hostname=foo.ddns.foo.com&myip=x.x.x.x HTTP/1.0" 301 169 "-" "ddclient/3.9.1"
but there is no update on server .

I have made change in config , you shoud change also in instructions ...

protocol=dyndns2
use=web, web=checkip.dyndns.com, web-skip='Current IP Address:'
server=ddns.foo.com
ssl=no
login=user
password='password'
foo.ddns.foo.com

Best regards

**Comment by olimpo88** [comment]
You should not touch the docker bind setting (I indicate this in case you did).

Can't you see the IP update from the web interface?
From your client console try running
`
ddclient --force
`
`
dig foo.ddns.foo.com @SERVERIP
`

**Comment by cpedja** [comment]
Thanks for a quick answer. 
Windows client update without problem , so i think that there is no problem with tempering with a bind settings.I would gladly avoid to run windows machine just to update ddns.  Without inserting a ip in soa record only my primary dns have a record of a ddns server . 
this i have added in my primary .zone conf 

ddns.foo.com.     IN	A	x.x.x.x
$ORIGIN ddns.foo.com.
@                       IN      NS	ddns.foo.com.

and without tempering in bind settings , public dns record won`t update .

i have tryed with force , this is result (if wrong ip exist in web interface, without is no reply ) 

sudo ddclient --force
WARNING:  file /var/cache/ddclient/ddclient.cache, line 3: Invalid Value for keyword 'ip' = ''

i have create 2 domains foo1.ddns.foo.com and foo2.ddns.foo.com , first is written in a .zone file /data/bind-data/foo.zone  and second is not . 
if i try to dig from localhost it is same result as in a web interface .

my ddns server is virtual machine because i don`t wont to give root access to some app . i have forward this ports
tcp+udp 53 , tcp 80 ,tcp 443, tcp 8080 as instructed.

Thanks in advance.
Best regards

**Comment by olimpo88** [comment]
Please, start the project again following the indicated steps, you can use a new folder so as not to lose what you have and try everything on your local network without using your public DNS.

in your client configure the internal IP of your server.

Once you can do
dig foo.ddns.foo.com @ SERVER-INTERNAL-IP

and it works as expected, at that time you must configure your public DNS with the NS zone, that way you can quickly identify the problem.

**Comment by olimpo88** [comment]
Hi @cpedja, Could you solve your problem?
