### ISSUE TITLE
Update URL gives error "The APP not sinc bind"

### ISSUE THREAD

**Issue by jacotec** [olimpo88/PyDDNS#26]
I want to use the DDNS update natively on some routers (running a PC client everywhere is not comfortable). In nearly all cases you need to provide an update URL.

Following the docker DDNS doc, I've configured a test with the update URL:

https://ddns.mydomain.de/nic/update?hostname=subdomain.ddns.mydomain.de

The client in the router is happy with this, but the PyDDNS lists the error "The APP not sinc bind" (whatever this means).

<img width="1108" alt="2021-05-29_13-08-22" src="https://user-images.githubusercontent.com/3321655/120068055-0019c300-c07f-11eb-9ab4-e3a6b6a0635f.png">

Is there an issue with the update URL, or what's causing the problem?

**Comment by jacotec** [comment]
My fault, correct URL is:

https://ddns.mydomain.de/nic/update?hostname=subdomain.ddns.mydomain.de&myip={IP_ADDRESS}.

Leaving this issue to give info to others with the same problem.

**Comment by olimpo88** [comment]
You must add the DNS record in your DNS not in the DDNS.

You have a DNS for demo.com where to add your record to your MX for emails and define subdomains, in that DNS you must add the subdomain ddns.demo.com (example) and indicate with an NS record that all queries from that subdomain will be answered by DDNS.
