### ISSUE TITLE
Doc for static/glue records unclear, zone file does not exist

### ISSUE THREAD

**Issue by jacotec** [olimpo88/PyDDNS#27]
I need to add a static record to the DNS server and following the doc I need to add the entry in data/bind-data/ddns.mydomain.de.zone in the ddns container.

There is no such file!

The only zone file in the whole container is: /var/cache/bind/ddns.mydomain.de.zone

Editing this file works, but I doubt it will survive reboots. Can you please clarify the doc about adding static records?

**Comment by olimpo88** [comment]
You must add the DNS record in your DNS not in the DDNS.

You have a DNS for demo.com where to add your record to your MX for emails and define subdomains, in that DNS you must add the subdomain ddns.demo.com (example) and indicate with an NS record that all queries from that subdomain will be answered by DDNS.

**Comment by jacotec** [comment]
That's what I did. Here is the record of the main domain for the DDNS (let's call it mydomain.de):

```
;
; Zone Records
;
@ 	 IN NS 	dns.domain1.de.
@ 	 IN A 	1.2.3.4
@ 	 IN NS  	oxygen.ns.hetzner.com.
@ 	 IN NS  	hydrogen.ns.hetzner.com.
ddns 	 IN A  	3.4.5.6
*.ddns 	 IN NS  	ddns.mydomain.de.
```

3.4.5.6 is the IP where the PyDNS server is running.

But the main DNS server which covers the domain with the above entries is not responding to requests for ddns.mydomain.de, these are also sent to the DDNS server ddns.mydomain.de

This issue is: Everything with "*.ddns.mydomain.de" is resolved by the PyDDNS server. Which is the plan and which works well.

But: Any DNS requests for ddns.mydomain.de (which hosts the GUI and update URLs) are also sent to the PyDDNS server - and this is unfortunately not responding to queries for ddns.mydomain.de, only for the DDNS subdomains created by the users.

So, to get that working the PyDDNS must also respond to A requests for "ddns.mydomain.de" with it's own IP address. It's not doing this.

Adding the

@ IN A 3.4.5.6

to /var/cache/bind/ddns.mydomain.de.zone resolves the issue and all is working. Without this, all DNS requests for ddns.mydomain.de itself do not return an IP address, so the GUI and update URL's are not working.

**Comment by olimpo88** [comment]
Oh now i understand.

Generally, two domains are used, ddns.demo.com to resolve and another more friendly one, for example myip.ddns.com that points to the web interface.

Adding an A record for myip.ddns.com in your DNS solves that problem.

**Comment by jacotec** [comment]
Got it, thanks! :-)

**Comment by olimpo88** [comment]
You're welcome, I'll add this in the documentaction.
