### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by Brian040101** [olimpo88/PyDDNS#29]
ab040101@ab040101-desktop:~/pyddns/PyDDNS$ sudo docker-compose up
WARNING: The MAX_DOMAINS_USER variable is not set. Defaulting to a blank string.
pyddns_ddns_1 is up-to-date
pyddns_postgres_1 is up-to-date
pyddns_python_1 is up-to-date
Recreating pyddns_nginx_1 ...
Recreating pyddns_nginx_1 ... done
Attaching to pyddns_ddns_1, pyddns_postgres_1, pyddns_python_1, pyddns_nginx_1
nginx_1     | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx_1     | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx_1     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx_1     | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
nginx_1     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx_1     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx_1     | /docker-entrypoint.sh: Configuration complete; ready for start up
nginx_1     | 2021/07/05 15:14:42 [emerg] 1#1: cannot load certificate "/etc/nginx/certs/https.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/certs/https.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx_1     | nginx: [emerg] cannot load certificate "/etc/nginx/certs/https.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/certs/https.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
postgres_1  | The files belonging to this database system will be owned by user "postgres".
python_1    | wait-for-it.sh: waiting 15 seconds for postgres:5432
postgres_1  | This user must also own the server process.
python_1    | wait-for-it.sh: postgres:5432 is available after 8 seconds
postgres_1  |
postgres_1  | The database cluster will be initialized with locale "en_US.utf8".
postgres_1  | The default database encoding has accordingly been set to "UTF8".
python_1    | System check identified some issues:
python_1    |
python_1    | WARNINGS:
python_1    | pyddns.Profile: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
python_1    |   HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
python_1    | pyddns.SubDomain: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
postgres_1  | The default text search configuration will be set to "english".
python_1    |   HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
postgres_1  |
python_1    | Migrations for 'common':
python_1    |   common/migrations/0001_initial.py
postgres_1  | Data page checksums are disabled.
python_1    |     - Create model Activity_log
postgres_1  |
python_1    | Migrations for 'pyddns':
postgres_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
python_1    |   pyddns/migrations/0001_initial.py
postgres_1  | creating subdirectories ... ok
python_1    |     - Create model SubDomain
python_1    |     - Create model Profile
python_1    | /script/runserver.sh: line 10:    34 Segmentation fault      (core dumped) python manage.py makemigrations
python_1    | Operations to perform:
postgres_1  | selecting default max_connections ... 100
python_1    |   Apply all migrations: admin, auth, common, contenttypes, pyddns, sessions
postgres_1  | selecting default shared_buffers ... 128MB
python_1    | Running migrations:
postgres_1  | selecting default timezone ... Etc/UTC
postgres_1  | selecting dynamic shared memory implementation ... posix
postgres_1  | creating configuration files ... ok
python_1    |   Applying contenttypes.0001_initial... OK
postgres_1  | running bootstrap script ... ok
python_1    |   Applying auth.0001_initial... OK
postgres_1  | performing post-bootstrap initialization ... ok
python_1    |   Applying admin.0001_initial... OK
postgres_1  | syncing data to disk ... ok
python_1    |   Applying admin.0002_logentry_remove_auto_add... OK
postgres_1  |
python_1    |   Applying admin.0003_logentry_add_action_flag_choices... OK
python_1    |   Applying contenttypes.0002_remove_content_type_name... OK
python_1    |   Applying auth.0002_alter_permission_name_max_length... OK
python_1    |   Applying auth.0003_alter_user_email_max_length... OK
python_1    |   Applying auth.0004_alter_user_username_opts... OK
postgres_1  | Success. You can now start the database server using:
postgres_1  |
python_1    |   Applying auth.0005_alter_user_last_login_null... OK
postgres_1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
python_1    |   Applying auth.0006_require_contenttypes_0002... OK
postgres_1  |
python_1    |   Applying auth.0007_alter_validators_add_error_messages... OK
postgres_1  |
python_1    |   Applying auth.0008_alter_user_username_max_length... OK
postgres_1  | WARNING: enabling "trust" authentication for local connections
python_1    |   Applying auth.0009_alter_user_last_name_max_length... OK
postgres_1  | You can change this by editing pg_hba.conf or using the option -A, or
python_1    |   Applying auth.0010_alter_group_name_max_length... OK
postgres_1  | --auth-local and --auth-host, the next time you run initdb.
python_1    |   Applying auth.0011_update_proxy_permissions... OK
postgres_1  | waiting for server to start....LOG:  database system was shut down at 2021-07-05 15:07:25 UTC
python_1    |   Applying auth.0012_alter_user_first_name_max_length... OK
postgres_1  | LOG:  MultiXact member wraparound protections are now enabled
python_1    |   Applying common.0001_initial... OK
postgres_1  | LOG:  autovacuum launcher started
python_1    |   Applying pyddns.0001_initial... OK
postgres_1  | LOG:  database system is ready to accept connections
python_1    | System check identified some issues:
postgres_1  |  done
python_1    |
postgres_1  | server started
python_1    | WARNINGS:
postgres_1  | CREATE DATABASE
postgres_1  |
python_1    | pyddns.Profile: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
python_1    |   HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
postgres_1  |
python_1    | pyddns.SubDomain: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
postgres_1  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
python_1    |   HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
postgres_1  |
python_1    |   Applying sessions.0001_initial... OK
postgres_1  | LOG:  received fast shutdown request
python_1    | /script/runserver.sh: line 11:    35 Segmentation fault      (core dumped) python manage.py migrate --noinput
postgres_1  | LOG:  aborting any active transactions
python_1    | /script/runserver.sh: line 15:    36 Done                    echo "from django.contrib.auth.models import User; User.objects.filter(username='$DJANGO_SU_NAME').exists() or  User.objects.create_superuser('$DJANGO_SU_NAME', '$DJANGO_SU_EMAIL', '$DJANGO_SU_PASSWORD')"
postgres_1  | waiting for server to shut down....LOG:  autovacuum launcher shutting down
python_1    |         37 Segmentation fault      (core dumped) | python manage.py shell
postgres_1  | LOG:  shutting down
python_1    | Watching for file changes with StatReloader
postgres_1  | LOG:  database system is shut down
python_1    | System check identified some issues:
postgres_1  |  done
python_1    |
postgres_1  | server stopped
postgres_1  |
python_1    | WARNINGS:
python_1    | pyddns.Profile: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
python_1    |   HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
python_1    | pyddns.SubDomain: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
python_1    |   HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
python_1    |
python_1    | System check identified 2 issues (0 silenced).
postgres_1  | PostgreSQL init process complete; ready for start up.
postgres_1  |
postgres_1  | LOG:  database system was shut down at 2021-07-05 15:07:29 UTC
postgres_1  | LOG:  MultiXact member wraparound protections are now enabled
postgres_1  | LOG:  autovacuum launcher started
postgres_1  | LOG:  database system is ready to accept connections
postgres_1  | LOG:  incomplete startup packet
pyddns_nginx_1 exited with code 1
pyddns_ddns_1 exited with code 1
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
pyddns_ddns_1 exited with code 1
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
pyddns_ddns_1 exited with code 1
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
pyddns_ddns_1 exited with code 1
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error

i use an arm computer(NVIDIA Jetson Nano), after i follow your step, the server can't work, can somebody give me some idea?

**Comment by olimpo88** [comment]
You can try in a virtual machine that is not arm, it may be that in the arm architecture some library is not compatible.

I see that your base starts up and initializes fine.

**Comment by Brian040101** [comment]
After i use an amd64 computer to rerun the scripts, it's appear another problem
brian@brian-H270-Gaming-3:~/PyDDNS$ sudo docker-compose up
WARNING: The MAX_DOMAINS_USER variable is not set. Defaulting to a blank string.
pyddns_postgres_1 is up-to-date
pyddns_ddns_1 is up-to-date
pyddns_python_1 is up-to-date
Starting pyddns_nginx_1 ... done
Attaching to pyddns_postgres_1, pyddns_ddns_1, pyddns_python_1, pyddns_nginx_1
nginx_1     | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx_1     | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx_1     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
ddns_1      | creating zone...
ddns_1      | creating REST api config...
ddns_1      | Starting domain name service...: bind9.
ddns_1      | 2021/07/06 02:55:00 Serving dyndns REST services on 0.0.0.0:8080...
nginx_1     | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
nginx_1     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
python_1    | wait-for-it.sh: waiting 15 seconds for postgres:5432
python_1    | wait-for-it.sh: postgres:5432 is available after 4 seconds
python_1    | System check identified some issues:
python_1    | 
python_1    | WARNINGS:
python_1    | pyddns.Profile: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
python_1    | 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
python_1    | pyddns.SubDomain: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
python_1    | 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
python_1    | Migrations for 'common':
python_1    |   common/migrations/0001_initial.py
python_1    |     - Create model Activity_log
python_1    | Migrations for 'pyddns':
python_1    |   pyddns/migrations/0001_initial.py
python_1    |     - Create model SubDomain
python_1    |     - Create model Profile
python_1    | Operations to perform:
python_1    |   Apply all migrations: admin, auth, common, contenttypes, pyddns, sessions
python_1    | Running migrations:
python_1    |   Applying contenttypes.0001_initial... OK
python_1    |   Applying auth.0001_initial... OK
python_1    |   Applying admin.0001_initial... OK
python_1    |   Applying admin.0002_logentry_remove_auto_add... OK
python_1    |   Applying admin.0003_logentry_add_action_flag_choices... OK
python_1    |   Applying contenttypes.0002_remove_content_type_name... OK
python_1    |   Applying auth.0002_alter_permission_name_max_length... OK
python_1    |   Applying auth.0003_alter_user_email_max_length... OK
python_1    |   Applying auth.0004_alter_user_username_opts... OK
python_1    |   Applying auth.0005_alter_user_last_login_null... OK
python_1    |   Applying auth.0006_require_contenttypes_0002... OK
python_1    |   Applying auth.0007_alter_validators_add_error_messages... OK
python_1    |   Applying auth.0008_alter_user_username_max_length... OK
python_1    |   Applying auth.0009_alter_user_last_name_max_length... OK
python_1    |   Applying auth.0010_alter_group_name_max_length... OK
python_1    |   Applying auth.0011_update_proxy_permissions... OK
python_1    |   Applying auth.0012_alter_user_first_name_max_length... OK
nginx_1     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
python_1    |   Applying common.0001_initial... OK
python_1    |   Applying pyddns.0001_initial... OK
python_1    |   Applying sessions.0001_initial... OK
python_1    | System check identified some issues:
python_1    | 
python_1    | WARNINGS:
python_1    | pyddns.Profile: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
python_1    | 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
python_1    | pyddns.SubDomain: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
python_1    | 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
python_1    | Watching for file changes with StatReloader
python_1    | System check identified some issues:
python_1    | 
python_1    | WARNINGS:
python_1    | pyddns.Profile: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
python_1    | 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
python_1    | pyddns.SubDomain: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
python_1    | 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
python_1    | 
python_1    | System check identified 2 issues (0 silenced).
python_1    | wait-for-it.sh: waiting 15 seconds for postgres:5432
python_1    | wait-for-it.sh: postgres:5432 is available after 3 seconds
python_1    | No changes detected
python_1    | System check identified some issues:
python_1    | 
python_1    | WARNINGS:
python_1    | pyddns.Profile: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
python_1    | 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
python_1    | pyddns.SubDomain: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
python_1    | 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
python_1    | System check identified some issues:
python_1    | 
python_1    | WARNINGS:
python_1    | pyddns.Profile: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
python_1    | 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
python_1    | pyddns.SubDomain: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
python_1    | 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
python_1    | Operations to perform:
python_1    |   Apply all migrations: admin, auth, common, contenttypes, pyddns, sessions
python_1    | Running migrations:
python_1    |   No migrations to apply.
python_1    | Watching for file changes with StatReloader
python_1    | System check identified some issues:
python_1    | 
python_1    | WARNINGS:
python_1    | pyddns.Profile: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
python_1    | 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
python_1    | pyddns.SubDomain: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
python_1    | 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
python_1    | 
python_1    | System check identified 2 issues (0 silenced).
python_1    | wait-for-it.sh: waiting 15 seconds for postgres:5432
python_1    | wait-for-it.sh: postgres:5432 is available after 4 seconds
python_1    | No changes detected
python_1    | System check identified some issues:
python_1    | 
python_1    | WARNINGS:
python_1    | pyddns.Profile: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
python_1    | 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
python_1    | pyddns.SubDomain: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
nginx_1     | /docker-entrypoint.sh: Configuration complete; ready for start up
postgres_1  | The files belonging to this database system will be owned by user "postgres".
postgres_1  | This user must also own the server process.
postgres_1  | 
postgres_1  | The database cluster will be initialized with locale "en_US.utf8".
postgres_1  | The default database encoding has accordingly been set to "UTF8".
postgres_1  | The default text search configuration will be set to "english".
postgres_1  | 
postgres_1  | Data page checksums are disabled.
postgres_1  | 
postgres_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres_1  | creating subdirectories ... ok
postgres_1  | selecting default max_connections ... 100
postgres_1  | selecting default shared_buffers ... 128MB
postgres_1  | selecting default timezone ... Etc/UTC
postgres_1  | selecting dynamic shared memory implementation ... posix
postgres_1  | creating configuration files ... ok
postgres_1  | running bootstrap script ... ok
postgres_1  | performing post-bootstrap initialization ... ok
postgres_1  | syncing data to disk ... ok
postgres_1  | 
postgres_1  | Success. You can now start the database server using:
postgres_1  | 
postgres_1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres_1  | 
postgres_1  | 
postgres_1  | WARNING: enabling "trust" authentication for local connections
postgres_1  | You can change this by editing pg_hba.conf or using the option -A, or
postgres_1  | --auth-local and --auth-host, the next time you run initdb.
postgres_1  | waiting for server to start....LOG:  database system was shut down at 2021-07-06 01:47:40 UTC
postgres_1  | LOG:  MultiXact member wraparound protections are now enabled
postgres_1  | LOG:  autovacuum launcher started
postgres_1  | LOG:  database system is ready to accept connections
postgres_1  |  done
postgres_1  | server started
postgres_1  | CREATE DATABASE
postgres_1  | 
postgres_1  | 
postgres_1  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgres_1  | 
postgres_1  | LOG:  received fast shutdown request
postgres_1  | LOG:  aborting any active transactions
postgres_1  | waiting for server to shut down...LOG:  autovacuum launcher shutting down
postgres_1  | .LOG:  shutting down
postgres_1  | LOG:  database system is shut down
postgres_1  |  done
postgres_1  | server stopped
postgres_1  | 
postgres_1  | PostgreSQL init process complete; ready for start up.
postgres_1  | 
postgres_1  | LOG:  database system was shut down at 2021-07-06 01:47:46 UTC
postgres_1  | LOG:  incomplete startup packet
postgres_1  | LOG:  MultiXact member wraparound protections are now enabled
postgres_1  | LOG:  autovacuum launcher started
postgres_1  | LOG:  database system is ready to accept connections
postgres_1  | LOG:  received fast shutdown request
postgres_1  | LOG:  aborting any active transactions
postgres_1  | FATAL:  terminating connection due to administrator command
postgres_1  | LOG:  autovacuum launcher shutting down
postgres_1  | LOG:  shutting down
postgres_1  | LOG:  database system is shut down
postgres_1  | 
postgres_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1  | 
postgres_1  | LOG:  database system was shut down at 2021-07-06 02:11:51 UTC
postgres_1  | LOG:  incomplete startup packet
postgres_1  | LOG:  MultiXact member wraparound protections are now enabled
postgres_1  | LOG:  autovacuum launcher started
postgres_1  | LOG:  database system is ready to accept connections
postgres_1  | LOG:  received fast shutdown request
postgres_1  | LOG:  aborting any active transactions
postgres_1  | LOG:  autovacuum launcher shutting down
postgres_1  | FATAL:  terminating connection due to administrator command
postgres_1  | LOG:  shutting down
postgres_1  | LOG:  database system is shut down
postgres_1  | 
postgres_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1  | 
postgres_1  | LOG:  database system was shut down at 2021-07-06 02:46:52 UTC
postgres_1  | LOG:  incomplete startup packet
postgres_1  | LOG:  MultiXact member wraparound protections are now enabled
postgres_1  | LOG:  autovacuum launcher started
postgres_1  | LOG:  database system is ready to accept connections
python_1    | 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
python_1    | System check identified some issues:
python_1    | 
python_1    | WARNINGS:
python_1    | pyddns.Profile: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
python_1    | 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
python_1    | pyddns.SubDomain: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
python_1    | 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
python_1    | Operations to perform:
python_1    |   Apply all migrations: admin, auth, common, contenttypes, pyddns, sessions
python_1    | Running migrations:
python_1    |   No migrations to apply.
python_1    | Watching for file changes with StatReloader
python_1    | System check identified some issues:
python_1    | 
python_1    | WARNINGS:
python_1    | pyddns.Profile: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
python_1    | 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
python_1    | pyddns.SubDomain: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
python_1    | 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
python_1    | 
python_1    | System check identified 2 issues (0 silenced).
nginx_1     | 2021/07/06 03:24:12 [emerg] 1#1: cannot load certificate "/etc/nginx/certs/https.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/certs/https.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx_1     | nginx: [emerg] cannot load certificate "/etc/nginx/certs/https.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/certs/https.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
pyddns_nginx_1 exited with code 1

**Comment by olimpo88** [comment]
cannot load certificate "/etc/nginx/certs/https.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/certs/https.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)

Hi Brian, Please, verify that you followed the steps to create the SSL certificate.

<br>
### Create SSL certificate
As web today is almost required to have SSL the package is setup for that by default.

1. Create folder `mkdir -p data/certs/`
2. To generate a certificate do `openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout data/certs/https.key -out data/certs/https.crt`
3. Then send to your certificate authority and get the server.crt file back
4. Install the key and crt files into certificate store in `/data/certs`

<br><br>
### Running without SSL
It is not recomended to run without SSL but if you wish to

Edit `/config/nginx/mydjango.conf` and comment this line:
```
return 302 https://$host$request_uri;
```

**Comment by olimpo88** [comment]
Hello @Brian040101 , were you able to solve the problem?

**Comment by Brian040101** [comment]
Yes,i finally solved!!! The website has been created, but i need to find out my nameserver to connect with my dns server.

**Comment by olimpo88** [comment]
Perfect!!! @Brian040101   :clap: :clap: :clap:

You must configure your DNS server with an NS record see the step-by-step instructions.

https://github.com/olimpo88/PyDDNS#configuration-of-dns

I will close this issue, you can open another one if you need it. 

---------------------------------------------------
The project is OpenSource, I spend many hours maintaining and updating it, I would appreciate if you could take 5 minutes and validate my knowledge. (aptitudes). :ballot_box_with_check:
https://www.linkedin.com/in/peraltaleandro/
