### ISSUE TITLE
Errors when running

### ISSUE THREAD

**Issue by Error1404** [olimpo88/PyDDNS#33]
Hi, 
Been trying to set this up and keep getting the following errors when it runs. 

python_1    | WARNINGS:
python_1    | pyddns.Profile: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
python_1    | 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
python_1    | pyddns.SubDomain: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
python_1    | 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
ddns_1      | standard_init_linux.go:228: exec user process caused: exec format error
pyddns_ddns_1 exited with code 1

Any ideas? Im sure its something simple that I have/havent done!

Thanks

**Comment by AaronJFoster** [comment]
I did come across the same issue and forked here with a fix: https://github.com/AaronJFoster/PyDDNS

**Comment by olimpo88** [comment]
Sorry for the delay, it's been a busy week.
@AaronJFoster. Do you want to send a pull request?

**Comment by olimpo88** [comment]
I see, when new docker images are created, the latest version of Django is being downloaded, that's why it started giving that warning, it has already been solved.

Thanks @AaronJFoster
