### ISSUE TITLE
Problem with DynDNS config on Router (dont work)

### ISSUE THREAD

**Issue by gomesOseias** [olimpo88/PyDDNS#40]
Using Windows and Linux clients things work fine, but I haven't found a working way for my router.

![image](https://github.com/olimpo88/PyDDNS/assets/56198860/2b76900f-f595-44aa-a99f-eb50fe9ad791)

**Comment by olimpo88** [comment]
Hi @gomesOseias, that is because your router does not support custom servers, when you select DynDNS it is not the DynDNS protocol, that means that your request will be made against that provider's servers instead of yours.
Other routers allow you to fill the URL with your server address.

**Comment by gomesOseias** [comment]
I understand, in fact it was my mistake. I sort of figured this out when I didn't see a field for "url server", thanks for confirming my question!

**Comment by gomesOseias** [comment]
thanks!

**Comment by gomesOseias** [comment]
thanks!
