### ISSUE TITLE
Windows DDNS client

### ISSUE THREAD

**Issue by shimuldn** [olimpo88/PyDDNS#6]
The windows client dydns field value change back to members.dyndns.org after clicking save. Is there any other app?

**Comment by olimpo88** [comment]
Are you using the recommended client?

https://sourceforge.net/projects/dyndnssimplycl/

What version of windows do you have?

Did you try running the client with administrator permissions?

**Comment by olimpo88** [comment]
I consulted a company that has PYDDNS with windows clients, they detected that the client "DynDNS Simply Client" has a bug.

That which you indicate occurs when many instances of the application are opened.

**Comment by olimpo88** [comment]
I tried this other client based in ddclient and it works great.

http://www.randomnoun.com/wp/2013/08/19/a-dynamic-dns-client-for-windows/

Important!!! open the configuration file and check be like this

```
deamon=5m
protocol=dyndns2
use=web, web=checkip.dyndns.com, web-skip='IP Address'
server=localhost.com
ssl=no
login=userdemo
password='userpassword'
yourdomain.ddns.demo.com
```

**Comment by olimpo88** [comment]
Two weeks passed and there are no comments, I close this and if it is of interest to you, reopen another case.
