### ISSUE TITLE
Add NS record in cloudflare

### ISSUE THREAD

**Issue by shimuldn** [olimpo88/PyDDNS#7]
How can I create an NS record to an IP address?

cloudflare.com says:
DNS Validation Error (Code: 1004) Content for NS record is invalid

Namecheap as an error when I put IP on the field. 

NS filed are allow only domain or subdomain name right?

**Comment by olimpo88** [comment]
I don't know your cloud platform, you should consult your provider, you have to do an NS registration for your subdomain

check this: https://www.cloudflare.com/learning/dns/dns-records/dns-ns-record/



this example is for bind:

ns3.ddns.demo.com.	IN	A	X.X.X.X
$ORIGIN ddns.ddns.demo.com.
@                       IN NS   ns3.ddns.demo.com.

**Comment by olimpo88** [comment]
Were you able to solve the problem?

**Comment by shimuldn** [comment]
In progress.. Will update here

**Comment by shimuldn** [comment]
I tried like this:
```
ns1.demo.com A -> server ip address
ddns.demo.com NS -> ns1.demo.com
```


```
deamon=5m
protocol=dyndns2
use=web, web=checkip.dyndns.com, web-skip='IP Address'
server=ns1.demo.com
ssl=no
login=userdemo
password='userpassword'
test.ddns.demo.com
```
Now working
Now working

**Comment by shimuldn** [comment]
How can i do `ddns.demo.com A --> server ip` so i can access my admin page on ddns.demo.com?

**Comment by olimpo88** [comment]
It's not that simple, instead you can create an **A** record with some friendly name, for example **myip.demo.com**

**Comment by shimuldn** [comment]
Got it.

Just created A record on `PyDDNS/data/bind-data/ddns.pussmail.com.zone`
```
NS      localhost.
IN A    server Ip Address

```
Now, ddns.demo.com is my admin page.

Thank You for the help.
