### ISSUE TITLE
Change default language

### ISSUE THREAD

**Issue by shimuldn** [olimpo88/PyDDNS#8]
The only language work is Spanish but my browser and the computer default language are English.
How can I change it to English?

**Comment by olimpo88** [comment]
That is strange, could you tell me what is your operating system, name and version of your browser to correct that problem?

You can also change the default language:

- open file --> nano ~/PyDDNS/appdata/pyddns/pyddns/settings.py
- change the variable in line 149/185 to --> LANGUAGE_CODE = 'en-En'

**Comment by shimuldn** [comment]
Ubuntu 18.04.4 and 20.04 default language was set to es-Es.
to get the appdata folder I had to create user and user a little bit. 
Problem solved.

**Comment by olimpo88** [comment]
Thanks for sharing your solution @shimuldn 

I would appreciate if it could take 5 minutes and validate my knowledge (aptitudes). :ballot_box_with_check:
https://www.linkedin.com/in/peraltaleandro/

**Comment by shimuldn** [comment]
Will do for sure.
