### ISSUE TITLE
skipped: IP address was already set

### ISSUE THREAD

**Issue by shimuldn** [olimpo88/PyDDNS#9]
When i was playing with the admin interface clicked `update to IP address (My current Ip address as per browser)`.
So the IP changed to my IP address but the ddclient not updating the IP address back to the server IP.

`skipped: IP address was already set to .... (old IP address before I clicked update to my IP)`

I understand I have to update ddclient config to force an update by ignoring the catch file or something.

If you have any idea a quick fix about that.

Thanks

**Comment by olimpo88** [comment]
You can use this command:

`sudo ddclient --force`

**Comment by shimuldn** [comment]
Thank You
